name: SLZB-06Mg26 OpenThread RCP
device: EFR32MG26B420F3200IM48
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_rcp_version.split('/')[-1]}_gsdk_{sdk_version}_{baudrate}"
sdk: "simplicity_sdk:2025.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: openthread_rcp
  ot_rcp_version: dynamic
  baudrate: 460800

c_defines:
  SL_CLOCK_MANAGER_HFXO_EN: 1
  SL_CLOCK_MANAGER_HFXO_CTUNE: 140
  SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE: SL_CLOCK_MANAGER_DEFAULT_HF_CLOCK_SOURCE_HFXO

  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL: EUSART0
  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL_NO: 0
  SL_IOSTREAM_EUSART_VCOM_FLOW_CONTROL_TYPE: SL_IOSTREAM_EUSART_UART_FLOW_CTRL_NONE
  SL_IOSTREAM_EUSART_VCOM_BAUDRATE: 460800

  SL_IOSTREAM_EUSART_VCOM_TX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_TX_PIN: 5
  SL_IOSTREAM_EUSART_VCOM_RX_PORT: SL_GPIO_PORT_A
  SL_IOSTREAM_EUSART_VCOM_RX_PIN: 6
  SL_IOSTREAM_EUSART_VCOM_CTS_PORT: 0
  SL_IOSTREAM_EUSART_VCOM_CTS_PIN: 0
  SL_IOSTREAM_EUSART_VCOM_RTS_PORT: 0
  SL_IOSTREAM_EUSART_VCOM_RTS_PIN: 0
  SL_IOSTREAM_EUSART_VCOM_RX_BUFFER_SIZE: 512